### ISSUE TITLE
Visuals and UI

### ISSUE THREAD

**Issue by bimbifan** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#122]
### Describe your bug here.

I don't know how to label this. Opponent hit count and rating counter cannot work separately.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm not using source code

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

**Comment by JordanSantiagoYT** [comment]
that's intentional.
![Cannot read](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/b054dad5-4df7-47f8-82d1-8f0c4456cb5b)

Please read what each option actually does before making an issue about it. The option clearly says you need the rating counter enabled for it to work
